### ISSUE TITLE
SettingsSingleFileGenerator with new csproj format

### ISSUE THREAD

**Issue by danstur** [Microsoft/msbuild#2782]
### Steps to reproduce
Not sure this is the right repo, but this seems similar to #1688 . 

I want to use the new csproj format for .NET 4.5.2 in Visual Studio 2017. The problem is that the SettingsSingleFileGenerator does not work. 

Project file
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net452</TargetFramework>
    <RootNamespace>TestProject</RootNamespace>
    <AssemblyName>TestProject</AssemblyName>
    <OutputType>Exe</OutputType>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
    <GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
    <GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.ServiceProcess" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\ApplicationSettings.settings" Generator="SettingsSingleFileGenerator" LastGenOutput="ApplicationSettings.Designer.cs" />
    <Compile Update="Properties\ApplicationSettings.Designer.cs" AutoGen="True" DependentUpon="ApplicationSettings.settings" />
  </ItemGroup>
</Project>
```

Directory contents:
```
/
   - Test.csproj
/Properties
   - ApplicationSettings.settings
   - ApplicationSettings.Designer.cs
```

ApplicationSettings.settings
```xml
<?xml version='1.0' encoding='utf-8'?>
<SettingsFile xmlns="http://schemas.microsoft.com/VisualStudio/2004/01/settings" CurrentProfile="(Default)" GeneratedClassNamespace="Test.Properties" GeneratedClassName="ApplicationSettings">
  <Profiles />
  <Settings>
    <Setting Name="Protocol" Type="System.String" Scope="User">
      <Value Profile="(Default)">HTTPS</Value>
    </Setting>
  </Settings>
</SettingsFile>
```

In Visual Studio rightclick ApplicationSettings.settings and choose "Run Custom Tool"

### Expected  behavior
The ApplicationSettings.Designer.cs is updated with the tool output.

### Actual behavior
Nothing happens. No error message or similar is generated, but the ApplicationSettings.Designer.cs file is not changed. When copying the ApplicationSettings.settings into an old csproj library and running the custom tool there the output is generated as expected, so the file itself is correct.

### Environment data
Visual Studio 2017 15.4.3
OS info:
Windows 10 1703

**Comment by jeremyVignelles** [comment]
Same thing here. Can anyone confirm this is the right place to ask?

**Comment by alexreinking** [comment]
I'm also running into this issue and can't seem to find a solution

**Comment by magol** [comment]
+1

**Comment by rainersigwald** [comment]
I suspect that this is related to https://github.com/dotnet/project-system/issues/218 -- @panopticoncentral, does that sound right to you?

**Comment by panopticoncentral** [comment]
Yes, I believe so.

**Comment by FixFever** [comment]
It looks like the bug is fixed, check.
Visual Studio 15.7.2.

**Comment by odalet** [comment]
Sorry to say, but it's not fixed... I just tested it in a new netcore app project (so that I have a bootstrap Sdk style project) that I targeted to net471.  The **ResXFileCodeGenerator** works just fine, but the **SettingsSingleFileGenerator** produces no output.

For the records here is my csproj:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net471</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System">
      <HintPath>System</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>
```

And my settings file:

```xml
<?xml version='1.0' encoding='utf-8'?>
<SettingsFile xmlns="http://schemas.microsoft.com/VisualStudio/2004/01/settings" CurrentProfile="(Default)" GeneratedClassNamespace="ConsoleApp1.Properties" GeneratedClassName="Settings">
  <Profiles />
  <Settings>
    <Setting Name="Setting1" Type="System.String" Scope="User">
      <Value Profile="(Default)">Foo</Value>
    </Setting>
  </Settings>
</SettingsFile>
```

PS: to me, the expected behavior should be a Settings.Designer.cs **and updates to App.config**...

**Comment by rainersigwald** [comment]
If https://github.com/dotnet/project-system/issues/218#issuecomment-232178054 is up to date, I don't think `SettingsSingleFileGenerator` is expected to work yet.

Since this is a Visual Studio project system feature, rather than core MSBuild, I'm going to close this in favor of that bug.

**Comment by rainersigwald** [comment]
Duplicate of dotnet/project-system#218

**Comment by rainersigwald** [comment]
Duplicate of dotnet/project-system#3535
